apiVersion: apps/v1
kind: Deployment
metadata:
  name: fe
  namespace: demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fe
  template:
    metadata:
      labels:
        app: fe
    spec:
      containers:
      - name: fe
        image: nginx:alpine
        ports:
        - containerPort: 80
        volumeMounts:
        - name: html-volume
          mountPath: /usr/share/nginx/html
        - name: conf-volume
          mountPath: /etc/nginx/conf.d
      volumes:
      - name: html-volume
        configMap:
          name: fe-html
      - name: conf-volume
        configMap:
          name: fe-conf
