apiVersion: v1
kind: Pod
metadata:
  name: app-uses-secret-volume
  namespace: w10-security-lab
spec:
  securityContext:
    runAsNonRoot: true
    seccompProfile:
      type: RuntimeDefault
  containers:
    - name: app
      image: busybox:1.36
      command: ["sh", "-c", "while true; do date; cat /etc/demo-secret/username /etc/demo-secret/password; sleep 10; done"]
      securityContext:
        allowPrivilegeEscalation: false
        runAsNonRoot: true
        runAsUser: 1000
        readOnlyRootFilesystem: true
        capabilities:
          drop: ["ALL"]
      resources:
        requests:
          cpu: 20m
          memory: 32Mi
        limits:
          cpu: 50m
          memory: 64Mi
      volumeMounts:
        - name: demo-secret
          mountPath: /etc/demo-secret
          readOnly: true
  volumes:
    - name: demo-secret
      secret:
        secretName: demo-db-secret
