apiVersion: v1
kind: ServiceAccount
metadata:
  name: external-secrets-aws
  namespace: w10-security-lab
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::123456789012:role/w10-eso-secrets-reader
---
apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: aws-secrets-manager
  namespace: w10-security-lab
spec:
  provider:
    aws:
      service: SecretsManager
      region: us-east-1
      auth:
        jwt:
          serviceAccountRef:
            name: external-secrets-aws
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: demo-db-secret
  namespace: w10-security-lab
spec:
  refreshInterval: 30s
  secretStoreRef:
    name: aws-secrets-manager
    kind: SecretStore
  target:
    name: demo-db-secret
    creationPolicy: Owner
  data:
    - secretKey: username
      remoteRef:
        key: /w10/demo/db
        property: username
    - secretKey: password
      remoteRef:
        key: /w10/demo/db
        property: password
