apiVersion: v1
kind: ConfigMap
metadata:
  name: be-api-data
  namespace: demo
data:
  data.json: |
    {
      "status": "success",
      "timestamp": "2026-06-11T12:00:00Z",
      "message": "Hello from the Backend API! (Powered by Kubernetes ConfigMap)",
      "version": "1.0.0"
    }
