apiVersion: apps/v1
kind: Deployment
metadata:
  name: be
  namespace: demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: be
  template:
    metadata:
      labels:
        app: be
    spec:
      containers:
      - name: be
        image: nginx:alpine
        ports:
        - containerPort: 80
        volumeMounts:
        - name: api-data
          mountPath: /usr/share/nginx/html/api
      volumes:
      - name: api-data
        configMap:
          name: be-api-data
