apiVersion: v1
kind: Secret
metadata:
  name: alertmanager-api-email
  namespace: monitoring
type: Opaque
stringData:
  # Gmail: bật 2FA → tạo App Password tại https://myaccount.google.com/apppasswords
  smtp_password: "sdsw pkjh pwoa nwyh"
