apiVersion: v1
kind: ServiceAccount
metadata:
  name: viewer
  namespace: w10-security-lab
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: developer
  namespace: w10-security-lab
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: sre
  namespace: w10-security-lab
