apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: api-monitoring
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/bnuochthithuy/gitops.git
    path: k8s-api/monitoring
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
